project:
  type: website
  output-dir: docs

website:
  title: "Vanessa Salgado"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

