---
title: "About Me"
---

##  Currently 

I am currently on the job search for Data Analytics or Database management in an environmental or social sphere in the larger Los Angeles metro area. Aside from job searching, I have started my own business selling vintage cameras and watches. I have more details on that below.

This website is a work in progress, and I hope to update with each milestone or progress on my projects. 


## Eductional Background

Master of Environmental Data Science - University of California, Santa Barbara (June 2024)

University of California, Santa Barbara B.S Computer Science 2022

## Current Fascinations

::: panel-tabset
## Camera Business

My partner and I started this vintage camera business as a subdivision of his vintage reselling business. We resell 2000s cameras and film cameras to those who also want to capture memories through a vintage lens. You can find us on instagram [@MomentsOnDigi](https://www.instagram.com/momentsondigi/) or at local LA flea markets. 

## Vintage Watch Business

I love going to flea markets and I always seem to find the prettiest, daintiest watches. I would always get compliments on watches and wanted to share my love for watches at flea markets as well or on Etsy! 

## Productivity App


:::
